services:
  postgres_prod:
    image: bitnami/postgresql:latest
    container_name: habitflow-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    volumes:
      - postgres_data:/bitnami/postgresql

  postgres_test:
    image: bitnami/postgresql:latest
    container_name: postgres_test
    ports:
      - '5433:5432'
    environment:
      POSTGRESQL_USERNAME: ${TEST_POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${TEST_POSTGRES_DB}
volumes:
  postgres_data:
