services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: habitflow-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    volumes:
      - postgres_data:/bitnami/postgresql
volumes:
  postgres_data:
